package su.gov.headers.ui;

import com.intellij.openapi.Disposable;
import com.intellij.ui.JBSplitter;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jetbrains.annotations.NotNull;
import su.gov.headers.transform.TransformScriptModel;
import su.gov.headers.ui.scriptsEditor.ScriptsEditorPanel;
import su.gov.headers.ui.scriptsEditor.ScriptsListPanel;

import javax.swing.*;
import java.awt.*;
import java.util.List;


public class SettingsPanel implements Disposable {

    private JPanel mainPanel;

    private JBSplitter templateSplitter;

    private ScriptsListPanel scriptsListPanel;

    private ScriptsEditorPanel scriptsEditorPanel;

    public ScriptsListPanel getScriptsListPanel() {
        return scriptsListPanel;
    }

    public ScriptsEditorPanel getScriptsEditorPanel() {
        return scriptsEditorPanel;
    }

    private void createUIComponents() {
        this.scriptsListPanel = new ScriptsListPanel(this);
        this.scriptsEditorPanel = new ScriptsEditorPanel(this);
        templateSplitter = new JBSplitter(false, 0.2f);
        templateSplitter.setFirstComponent(this.scriptsListPanel);
        templateSplitter.setSecondComponent(this.scriptsEditorPanel.getPanel());
    }

    public void setTransformModels(@NotNull List<TransformScriptModel> models) {
        this.scriptsListPanel.setItems(models);
    }

    public List<TransformScriptModel> getTransformModels() {
        return this.scriptsListPanel.getItems();
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    @Override
    public void dispose() {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setMinimumSize(new Dimension(38, 158));
        mainPanel.setPreferredSize(new Dimension(38, 158));
        mainPanel.add(templateSplitter, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
